In [1]:
import pandas as pd
file_r = "/Users/josealmendarez/Downloads/ml-latest-small/movies.csv"

df = pd.read_csv(file_r)

df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [2]:
# Exploraci√≥n de datos (ED)
print("üìä Dimensiones del dataset:", df.shape)
print("\nüîé Primeras filas:")
print(df.head())

print("\nüìù Informaci√≥n general:")
print(df.info())

print("\nüìà Valores nulos por columna:")
print(df.isnull().sum())

print("\nüî¢ N√∫mero de valores √∫nicos por columna:")
print(df.nunique())

print("\nüé¨ Columnas disponibles:", df.columns.tolist())

# Estad√≠sticas descriptivas (solo si hubiera num√©ricas)
print("\nüìä Estad√≠sticas descriptivas:")
print(df.describe(include='all'))

# Distribuci√≥n de g√©neros
if "genres" in df.columns:
    genres = df["genres"].str.split("|").explode()
    print("\nüé≠ Top 10 g√©neros m√°s comunes:")
    print(genres.value_counts().head(10))

üìä Dimensiones del dataset: (9742, 3)

üîé Primeras filas:
   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

üìù Informaci√≥n general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB
None

üìà Valores nulos por columna:
movieId    0
title      0
genres     0
dtype: int64

üî¢ N√∫mero de valores √∫nicos por columna:
movieId    9742
title      9737
genres      951
dtype: int64

üé¨ Columnas disponibles: ['movieId', 'title', 'genres']

üìä Estad√≠sticas descriptivas:
              movieId        title genres
count     9742.000000         9742   9742
unique            NaN         9737    951
top               NaN  Emma (1996)  Drama
freq              NaN            2   1053
mean     42200.353623          NaN    NaN
std      52160.494854          NaN    NaN
min          1.000000          NaN    NaN
25%       3248.250000          NaN    NaN
50%       7300.000000          NaN    NaN
75%      76232.000000          NaN    NaN
max     193609.000000          NaN    NaN

üé≠ Top 10 g√©neros m√°s comunes:
genres
Drama        4361
Comedy       3756
Thriller     1894
Action       1828
Romance      1596
Adventure    1263
Crime        1199
Sci-Fi        980
Horror        978
Fantasy       779
Name: count, dtype: int64